<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Book::insert([
            [
                'title' => 'It Ends With Us',
                'author' => 'Coleen Hoover',
                'released_year' => 2016,
                'publisher' => 'Atria Books',
                'image' => 'book-image/1.jpg',
                'summary' => 'In this "brave and heartbreaking novel that digs its claws into you and doesn\'t let go, long after you\'ve finished it" (Anna Todd, New York Times bestselling author) from the #1 New York Times bestselling author of All Your Perfects, a workaholic with a too-good-to-be-true romance can\'t stop thinking about her first love.',
                'description' => '80% in good condition',
                'user_id' => 2,
                'sale_price' => 60000,
                'loan_price' => 10000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'Ugly Love',
                'author' => 'Coleen Hoover',
                'released_year' => 2014,
                'publisher' => 'Atria Books',
                'image' => 'book-image/2.jpg',
                'summary' => 'When Tate Collins meets airline pilot Miles Archer, she knows it isn’t love at first sight. They wouldn’t even go so far as to consider themselves friends. The only thing Tate and Miles have in common is an undeniable mutual attraction. Once their desires are out in the open, they realize they have the perfect set-up. He doesn’t want love, she doesn’t have time for love, so that just leaves the sex. Their arrangement could be surprisingly seamless, as long as Tate can stick to the only two rules Miles has for her.',
                'description' => '75% in good condition',
                'user_id' => 2,
                'sale_price' => 100000,
                'loan_price' => 12000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],

            [
                'title' => '400 Days',
                'author' => 'Chetan Bhagat',
                'released_year' => 2021,
                'publisher' => 'Westland Publications',
                'image' => 'book-image/3.jpg',
                'summary' => 'Welcome to 400 Days. A mystery and romance story like none other. An unputdownable tale of suspense, human relationships, love, friendship, the crazy world we live in and, above all, a mother\'s determination to never give up.',
                'description' => '85% in good condition',
                'user_id' => 1,
                'loan_price' => 10000,
                'sale_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'The Seven Husbands of Evelyn Hugo',
                'author' => 'Taylor Jenkins Reid',
                'released_year' => 2018,
                'publisher' => 'Washington Square Press',
                'image' => 'book-image/4.jpg',
                'summary' => 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her? Why now?',
                'description' => '90% in good condition',
                'user_id' => 3,
                'loan_price' => 12000,
                'sale_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            //
            [
                'title' => 'A Rip Through Time',
                'author' => 'Kelley Armstrong',
                'released_year' => 2022,
                'publisher' => 'Minotaur Books',
                'image' => 'book-image/5.jpg',
                'summary' => 'When Mallory wakes up in Catriona\'s body in 1869, she must put aside her shock and adjust quickly to the reality: life as a housemaid to an undertaker in Victorian Scotland. She soon discovers that her boss, Dr. Gray, also moonlights as a medical examiner and has just taken on an intriguing case, the strangulation of a young man, similar to the attack on herself. Her only hope is that catching the murderer can lead her back to her modern life . . . before it\'s too late.',
                'description' => '75% in good condition',
                'user_id' => 1,
                'sale_price' => 150000,
                'loan_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'Malibu Rising',
                'author' => 'Taylor Jenkins Reid',
                'released_year' => 2021,
                'publisher' => 'Ballantine Books',
                'image' => 'book-image/6.jpg',
                'summary' => 'Malibu Rising is a story about one unforgettable night in the life of a family: the night they each have to choose what they will keep from the people who made them... and what they will leave behind.',
                'description' => '85% in good condition',
                'user_id' => 1,
                'loan_price' => 15000,
                'sale_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'The Murder of Mr. Wickham',
                'author' => 'Claudia Gray',
                'released_year' => 2022,
                'publisher' => 'Vintage Publishing',
                'image' => 'book-image/7.jpg',
                'summary' => 'A summer house party turns into a whodunit when Mr. Wickham, one of literature’s most notorious villains, meets a sudden and suspicious end in this mystery featuring Jane Austen’s leading literary characters.',
                'description' => '95% in good condition',
                'user_id' => 3,
                'sale_price' => 165000,
                'loan_price' => 12000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'Breathless',
                'author' => 'Amy McCulloch',
                'released_year' => 2022,
                'publisher' => 'Anchor Books',
                'image' => 'book-image/8.jpg',
                'summary' => 'A high-altitude thriller that will take your breath away--Cecily Wong is on her most dangerous climb yet, miles above sea level. But the elements are nothing compared to one chilling truth: There\'s a killer on the mountain.',
                'description' => '100% in good condition',
                'user_id' => 1,
                'sale_price' => 180000,
                'loan_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'Near The Bone',
                'author' => 'Christina Henry',
                'released_year' => 2021,
                'publisher' => 'Berkley Books',
                'image' => 'book-image/9.jpg',
                'summary' => 'A woman trapped on a mountain attempts to survive more than one kind of monster, in a dread-inducing horror novel from the national bestselling author Christina Henry.',
                'description' => '95% in good condition',
                'user_id' => 2,
                'sale_price' => 175000,
                'loan_price' => 15000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'The Hate U give',
                'author' => 'Angie Thomas',
                'released_year' => 2017,
                'publisher' => 'Balzer & Bray',
                'image' => 'book-image/10.jpg',
                'summary' => 'Sixteen-year-old Starr Carter moves between two worlds: the poor neighborhood where she lives and the fancy suburban prep school she attends. The uneasy balance between these worlds is shattered when Starr witnesses the fatal shooting of her childhood best friend Khalil at the hands of a police officer. Khalil was unarmed.',
                'description' => '80% in good condition',
                'user_id' => 3,
                'sale_price' => 175000,
                'loan_price' => 15000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'title' => 'The Sun and Her Flowers',
                'author' => 'Rupi Kaur',
                'released_year' => 2017,
                'publisher' => 'Andrews McMeel Publishing',
                'image' => 'book-image/11.jpg',
                'summary' => 'Divided into five chapters and illustrated by Kaur, the sun and her flowers is a journey of wilting, falling, rooting, rising, and blooming. A celebration of love in all its forms. this is the recipe of life said my mother as she held me in her arms as I wept think of those flowers you plant in the garden each year they will teach you that people too must wilt fall root risen order to bloom.',
                'description' => '100% in good condition',
                'user_id' => 1,
                'sale_price' => 120000,
                'loan_price' => 10000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'title' => 'The Princess Saves Herself in This One',
                'author' => 'Amanda Lovelace',
                'released_year' => 2016,
                'publisher' => 'CreateSpace',
                'image' => 'book-image/12.jpg',
                'summary' => 'A poetry collection divided into four different parts: the princess, the damsel, the queen, & you. the princess, the damsel, & the queen piece together the life of the author in three stages, while you serves as a note to the reader & all of humankind. Explores life & all of its love, loss, grief, healing, empowerment, & inspirations.',
                'description' => '80% in good condition',
                'user_id' => 1,
                'sale_price' => NULL,
                'loan_price' => 13000,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'title' => 'Milk and Honey',
                'author' => 'Rupi Kaur',
                'released_year' => 2014,
                'publisher' => 'CreateSpace',
                'image' => 'book-image/13.jpg',
                'summary' => 'Milk and Honey is a collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity. It is split into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. \'milk and honey\' takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.',
                'description' => '75% in good condition',
                'user_id' => 1,
                'sale_price' => 100000,
                'loan_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'title' => 'White Knuckle',
                'author' => 'Steven Bruce',
                'released_year' => 2020,
                'publisher' => '1987 Books',
                'image' => 'book-image/14.jpg',
                'summary' => 'White Knuckle is a concise exposé of a severe childhood experience. Bruce\'s debut poetry collection, an autobiographical report on the reality of life in a poverty-stricken, drug and violence-fuelled environment, is a gut-wrenching composition of grief, loss, and abandonment at an early age. This powerful book is brutal, tragic, and moving: an essential read.',
                'description' => '85% in good condition',
                'user_id' => 2,
                'sale_price' => 95000,
                'loan_price' => 8000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'title' => 'Please Love Me At My Worst',
                'author' => 'Michaela Angemeer',
                'released_year' => 2021,
                'publisher' => 'Andrews McMeel Publishing',
                'image' => 'book-image/15.jpg',
                'summary' => 'Please Love Me At My Worst is a collection of four sections of poetry inspired by loneliness, unrequited love, and not being able to let go of past relationships. Written during the 2020 COVID-19 quarantine, the book is a reflection of what it means to yearn for people who are unavailable and how important it is to focus on self-love and healing.',
                'description' => '70% in good condition',
                'user_id' => 1,
                'loan_price' => 10000,
                'sale_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'title' => 'How to Prevent the Next Pandemic',
                'author' => 'Bill Gates',
                'released_year' => 2022,
                'publisher' => 'Knopf Publishing Group',
                'image' => 'book-image/16.jpg',
                'summary' => 'The COVID-19 pandemic isn\'t over. But even as governments around the world try to get it under control, they\'re also starting to talk about what happens next. How can we prevent another pandemic from killing millions of people and devastating the global economy? Can we even hope to accomplish this?',
                'description' => '100% in good condition',
                'user_id' => 3,
                'loan_price' => 15000,
                'sale_price' => 200000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Noah Harari',
                'released_year' => 2015,
                'publisher' => 'Vintage Publishing',
                'image' => 'book-image/17.jpg',
                'summary' => 'In Sapiens, Dr Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical – and sometimes devastating – breakthroughs of the Cognitive, Agricultural and Scientific Revolutions. Drawing on insights from biology, anthropology, paleontology and economics, he explores how the currents of history have shaped our human societies, the animals and plants around us, and even our personalities. Have we become happier as history has unfolded? Can we ever free our behaviour from the heritage of our ancestors? And what, if anything, can we do to influence the course of the centuries to come?',
                'description' => '65% in good condition',
                'user_id' => 1,
                'loan_price' => NULL,
                'sale_price' => 150000,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'title' => 'Internet for the People',
                'author' => 'Ben Tarnoff',
                'released_year' => 2022,
                'publisher' => 'Verso Publishing',
                'image' => 'book-image/18.jpg',
                'summary' => 'In Internet for the People, leading tech writer Ben Tarnoff offers an answer. The internet is broken, he argues, because it is owned by private firms and run for profit. Google annihilates your privacy and Facebook amplifies right-wing propaganda because it is profitable to do so. But the internet wasn\'t always like this—it had to be remade for the purposes of profit maximization, through a years-long process of privatization that turned a small research network into a powerhouse of global capitalism. Tarnoff tells the story of the privatization that made the modern internet, and which set in motion the crises that consume it today.',
                'description' => '100% in good condition',
                'user_id' => 1,
                'loan_price' => 15000,
                'sale_price' => 200000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'title' => 'Brief History of Equality',
                'author' => 'Thomas Piketty',
                'released_year' => 2021,
                'publisher' => 'Vintage Publishing',
                'image' => 'book-image/19.jpg',
                'summary' => 'The world\'s leading economist of inequality presents a short but sweeping and surprisingly optimistic history of human progress toward equality despite crises, disasters, and backsliding. A perfect introduction to the ideas developed in his monumental earlier books.',
                'description' => '95% in good condition',
                'user_id' => 1,
                'loan_price' => 13000,
                'sale_price' => 165000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'title' => 'The Gene: An Intimate History',
                'author' => 'Siddartha Mukherjee',
                'released_year' => 2016,
                'publisher' => 'Vintage Publishing',
                'image' => 'book-image/20.jpg',
                'summary' => 'This is an epic, moving history of a scientific idea coming to life, by the author of The Emperor of All Maladies. But woven through The Gene, like a red line, is also an intimate history – the story of Mukherjee’s own family and its recurring pattern of mental illness, reminding us that genetics is vitally relevant to everyday lives. These concerns reverberate even more urgently today as we learn to “read” and “write” the human genome – unleashing the potential to change the fates and identities of our children.',
                'description' => '85% in good condition',
                'user_id' => 1,
                'loan_price' => 12000,
                'sale_price' => 125000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'title' => 'Living Slower: Simple Ideas to Eliminate Excess and Make Time for What Matters',
                'author' => 'Merissa A. ALink',
                'released_year' => 2022,
                'publisher' => 'Baker Books',
                'image' => 'book-image/21.jpg',
                'summary' => 'In an increasingly complex and chaotic world, we yearn to live a little slower, a little simpler.',
                'description' => '85% in good condition',
                'user_id' => 1,
                'sale_price' => 135000,
                'loan_price' => 12000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'author' => 'Mark Manson',
                'released_year' => 2016,
                'publisher' => 'Harper Publishing',
                'image' => 'book-image/22.jpg',
                'summary' => 'There are only so many things we can give a f**k about so we need to figure out which ones really matter, Manson makes clear. While money is nice, caring about what you do with your life is better, because true wealth is about experience. A much-needed grab-you-by-the-shoulders-and-look-you-in-the-eye moment of real-talk, filled with entertaining stories and profane, ruthless humor, The Subtle Art of Not Giving a F**k is a refreshing slap for a generation to help them lead contented, grounded lives.',
                'description' => '80% in good condition',
                'user_id' => 2,
                'sale_price' => 125000,
                'loan_price' => 12000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => '12 rules for Life: An Antidote to Chaos',
                'author' => 'Jordan B. Peterson',
                'released_year' => 2018,
                'publisher' => 'Random House Canada',
                'image' => 'book-image/23.jpg',
                'summary' => 'What does everyone in the modern world need to know? Renowned psychologist Jordan B. Peterson\'s answer to this most difficult of questions uniquely combines the hard-won truths of ancient tradition with the stunning revelations of cutting-edge scientific research.',
                'description' => '80% in good condition',
                'user_id' => 1,
                'sale_price' => 145000,
                'loan_price' => 10000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'The Comfort Book',
                'author' => 'Matt Haig',
                'released_year' => 2021,
                'publisher' => 'Penguin Life',
                'image' => 'book-image/24.jpg',
                'summary' => 'The Comfort Book is Haig’s life raft: it’s a collection of notes, lists, and stories written over a span of several years that originally served as gentle reminders to Haig’s future self that things are not always as dark as they may seem. Incorporating a diverse array of sources from across the world, history, science, and his own experiences, Haig offers warmth and reassurance, reminding us to slow down and appreciate the beauty and unpredictability of existence.',
                'description' => '95% in good condition',
                'user_id' => 1,
                'sale_price' => NULL,
                'loan_price' => 13000,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'Maybe You Should Talk to Someone',
                'author' => 'Lori Gottlieb',
                'released_year' => 2019,
                'publisher' => 'Penguin Life',
                'image' => 'book-image/25.jpg',
                'summary' => 'Maybe You Should Talk to Someone is revolutionary in its candor, offering a deeply personal yet universal tour of our hearts and minds and providing the rarest of gifts: a boldly revealing portrait of what it means to be human, and a disarmingly funny and illuminating account of our own mysterious lives and our power to transform them.',
                'description' => '90% in good condition',
                'user_id' => 1,
                'sale_price' => NULL,
                'loan_price' => 14000,
                'status_id' => 1,
                'transaction_type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'Gender Queer',
                'author' => 'Maia Kobabe & Phoebe Kobabe',
                'released_year' => 2019,
                'publisher' => 'Oni Press',
                'image' => 'book-image/26.jpg',
                'summary' => 'In 2014, Maia Kobabe, who uses e/em/eir pronouns, thought that a comic of reading statistics would be the last autobiographical comic e would ever write. At the time, it was the only thing e felt comfortable with strangers knowing about em. Now, Gender Queer is here. Maia\'s intensely cathartic autobiography charts eir journey of self-identity, which includes the mortification and confusion of adolescent crushes, grappling with how to come out to family and society, bonding with friends over erotic gay fanfiction, and facing the trauma of pap smears. Started as a way to explain to eir family what it means to be nonbinary and asexual, Gender Queer is more than a personal story: it is a useful and touching guide on gender identity--what it means and how to think about it--for advocates, friends, and humans everywhere.',
                'description' => '85% in good condition',
                'user_id' => 3,
                'sale_price' => 110000,
                'loan_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'Cheer Up: Love and Pompoms',
                'author' => 'Crystal Frasier',
                'released_year' => 2021,
                'publisher' => 'Oni Press',
                'image' => 'book-image/27.jpg',
                'summary' => 'Annie is a smart, antisocial lesbian starting her senior year of high school who’s under pressure to join the cheerleader squad to make friends and round out her college applications. Her former friend BeeBee is a people-pleaser—a trans girl who must keep her parents happy with her grades and social life to keep their support of her transition. Through the rigors of squad training and amped up social pressures (not to mention micro aggressions and other queer youth problems), the two girls rekindle a friendship they thought they’d lost and discover there may be other, sweeter feelings springing up between them. ',
                'description' => '95% in good condition',
                'user_id' => 1,
                'sale_price' => 115000,
                'loan_price' => 13000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'A Sign of Affection, Vol. 1',
                'author' => 'Suu Morishita',
                'released_year' => 2019,
                'publisher' => 'Kodansha Comics',
                'image' => 'book-image/28.jpg',
                'summary' => 'Yuki is a typical college student, whose world revolves around her friends, social media, and the latest sales. But when a chance encounter on a train leads to her meeting friend-of-a-friend and fellow student Itsuomi-san, her world starts to widen. But even though Itsuomi-kun can speak three languages, sign language isn\'t one of them. Can the two learn to communicate the budding feelings between them? ',
                'description' => '85% in good condition',
                'user_id' => 1,
                'sale_price' => 130000,
                'loan_price' => NULL,
                'status_id' => 2,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'Fanfirl, Vol. 2: The Manga',
                'author' => 'Sam Maggs & Rainbow Rowell',
                'released_year' => 2022,
                'publisher' => 'VIZ Media LLC',
                'image' => 'book-image/29.jpg',
                'summary' => 'Cath just wants to hang out with her twin sister and write fanfiction. But now that they’re at college, her sister doesn’t have time for her. And life keeps pulling Cath further and further out of her shell. For the first time ever, Cath has her own social circle. There’s Nick, her handsome classmate who wants her to write short stories with him… And then Levi, who keeps showing up when she isn’t looking for him … Actually … maybe Cath’s circle is more of a triangle?',
                'description' => '100% in good condition',
                'user_id' => 2,
                'sale_price' => 150000,
                'loan_price' => 13000,
                'status_id' => 1,
                'transaction_type_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'title' => 'Orange: The Complete Collection, Volume 1',
                'author' => 'Ichigo Takano',
                'released_year' => 2016,
                'publisher' => 'Seven Seas',
                'image' => 'book-image/30.jpg',
                'summary' => 'On the day that Naho begins 11th grade, she receives a letter from herself ten years in the future. At first, she writes it off as a prank, but as the letter’s predictions come true one by one, Naho realizes that the letter might be the real deal. Her future self tells Naho that a new transfer student, a boy named Kakeru, will soon join her class. The letter begs Naho to watch over him, saying that only Naho can save Kakeru from a terrible future. Who is this mystery boy, and can Naho save him from his destiny? This is the heart-wrenching sci-fi romance that has over million copies in print in Japan!',
                'description' => '70% in good condition',
                'user_id' => 3,
                'sale_price' => 125000,
                'loan_price' => NULL,
                'status_id' => 1,
                'transaction_type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],


        ]);
    }
}
